name: solana_mobile_common
description: Common interfaces for Solana protocols.
version: 0.0.1+1
repository: https://github.com/merigo-labs/solana-mobile-common

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  base_codecs: ^1.0.1
  synchronized: ^3.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0